config/routes.rb
Rails.application.routes.draw do
  resources :cuenta
  resources :distritos
  resources :operador_registros
  resources :metodo_pago_registros
  resources :vehiculo_registros
  resources :chofer_registros
  resources :tarifario_registros
  resources :feedback_registros
  resources :dirfavorita_registros
  resources :conductor_registros
  resources :cliente_registros
  resources :reservas

  get 'sesion/primario'

  get 'operator/admin'

  get 'iniciar/standar'

  get 'categoria/index'
  get 'iniciar/client'

  get 'iniciar/chofer'
  
  get 'operator/adminhome'
  

    root 'home#index'

end

app/models/chofer_registro.rb
class ChoferRegistro < ActiveRecord::Base
end

app/models/cliente_registro.rb
class ClienteRegistro < ActiveRecord::Base
end

app/models/conductor_registro.rb
class ConductorRegistro < ActiveRecord::Base
end

app/models/cuentum.rb
class Cuentum < ActiveRecord::Base
end

app/models/dirfavorita_registro.rb
class DirfavoritaRegistro < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
end

app/models/feedback_registro.rb
class FeedbackRegistro < ActiveRecord::Base
end

app/models/metodo_pago_registro.rb
class MetodoPagoRegistro < ActiveRecord::Base
end

app/models/operador_registro.rb
class OperadorRegistro < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
    belongs_to :categoria
end

app/models/tarifario_registro.rb
class TarifarioRegistro < ActiveRecord::Base
end

app/models/vehiculo_registro.rb
class VehiculoRegistro < ActiveRecord::Base
end

app/controllers/cuenta_controller.rb
class CuentaController < ApplicationController
  before_action :set_cuentum, only: [:show, :edit, :update, :destroy]

  # GET /cuenta
  # GET /cuenta.json
  def index
    @cuenta = Cuentum.all
  end

  # GET /cuenta/1
  # GET /cuenta/1.json
  def show
  end

  # GET /cuenta/new
  def new
    @cuentum = Cuentum.new
  end

  # GET /cuenta/1/edit
  def edit
  end

  # POST /cuenta
  # POST /cuenta.json
  def create
    @cuentum = Cuentum.new(cuentum_params)

    respond_to do |format|
      if @cuentum.save
        format.html { redirect_to @cuentum, notice: 'Cuentum was successfully created.' }
        format.json { render :show, status: :created, location: @cuentum }
      else
        format.html { render :new }
        format.json { render json: @cuentum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuenta/1
  # PATCH/PUT /cuenta/1.json
  def update
    respond_to do |format|
      if @cuentum.update(cuentum_params)
        format.html { redirect_to @cuentum, notice: 'Cuentum was successfully updated.' }
        format.json { render :show, status: :ok, location: @cuentum }
      else
        format.html { render :edit }
        format.json { render json: @cuentum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuenta/1
  # DELETE /cuenta/1.json
  def destroy
    @cuentum.destroy
    respond_to do |format|
      format.html { redirect_to cuenta_url, notice: 'Cuentum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuentum
      @cuentum = Cuentum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cuentum_params
      params.require(:cuentum).permit(:correo, :password)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)

    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:codigo, :direccion_origen, :distrito_origen, :direccion_destino, :distrito_destino, :cantidad_pasajeros, :categoria, :tarifa_final, :metodo_pago, :estado, :chofer, :usuario, :created, :updated)
    end
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iniciar_helper.rb
module IniciarHelper
end

app/helpers/operator_helper.rb
module OperatorHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sing_in_helper.rb
module SingInHelper
end

app/views/reservas/_form.html.erb
<%= simple_form_for(@reserva) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :codigo %>
    <%= f.input :direccion_origen %>
    <%= f.input :distrito_origen %>
    <%= f.input :direccion_destino %>
    <%= f.input :distrito_destino %>
    <%= f.input :cantidad_pasajeros %>
    <%= f.association :categoria, :as => :select %>
    <%= f.input :tarifa_final %>
    <%= f.input :metodo_pago %>
    <%= f.input :estado %>
    <%= f.input :chofer %>
    <%= f.input :usuario %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reservas/edit.html.erb
<h1>Modificar los datos de la Reserva</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserva %> |
<%= link_to 'Back', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relación de Reservas</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Direccion origen</th>
      <th>Distrito origen</th>
      <th>Direccion destino</th>
      <th>Distrito destino</th>
      <th>Cantidad pasajeros</th>
      <th>Categoria</th>
      <th>Tarifa final</th>
      <th>Metodo pago</th>
      <th>Estado</th>
      <th>Chofer</th>
      <th>Usuario</th>
      <th>Created</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.codigo %></td>
        <td><%= reserva.direccion_origen %></td>
        <td><%= reserva.distrito_origen %></td>
        <td><%= reserva.direccion_destino %></td>
        <td><%= reserva.distrito_destino %></td>
        <td><%= reserva.cantidad_pasajeros %></td>
        <td><%= reserva.categoria %></td>
        <td><%= reserva.tarifa_final %></td>
        <td><%= reserva.metodo_pago %></td>
        <td><%= reserva.estado %></td>
        <td><%= reserva.chofer %></td>
        <td><%= reserva.usuario %></td>
        <td><%= reserva.created %></td>
        <td><%= reserva.updated %></td>
        <td><%= link_to 'Show', reserva %></td>
        <td><%= link_to 'Edit', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Destroy', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Reserva', new_reserva_path %>

app/views/reservas/new.html.erb
<h1>Registrar un Reserva aqui...!</h1>

<%= render 'form' %>

<%= link_to 'Back', reservas_path %>

app/views/reservas/show.html.erb
<h1>Consultar los datos de la Reserva</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @reserva.codigo %>
</p>

<p>
  <strong>Direccion origen:</strong>
  <%= @reserva.direccion_origen %>
</p>

<p>
  <strong>Distrito origen:</strong>
  <%= @reserva.distrito_origen %>
</p>

<p>
  <strong>Direccion destino:</strong>
  <%= @reserva.direccion_destino %>
</p>

<p>
  <strong>Distrito destino:</strong>
  <%= @reserva.distrito_destino %>
</p>

<p>
  <strong>Cantidad pasajeros:</strong>
  <%= @reserva.cantidad_pasajeros %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @reserva.categoria %>
</p>

<p>
  <strong>Tarifa final:</strong>
  <%= @reserva.tarifa_final %>
</p>

<p>
  <strong>Metodo pago:</strong>
  <%= @reserva.metodo_pago %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @reserva.estado %>
</p>

<p>
  <strong>Chofer:</strong>
  <%= @reserva.chofer %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @reserva.usuario %>
</p>

<p>
  <strong>Created:</strong>
  <%= @reserva.created %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @reserva.updated %>
</p>

<%= link_to 'Edit', edit_reserva_path(@reserva) %> |
<%= link_to 'Back', reservas_path %>