config/routes.rb
Rails.application.routes.draw do
  resources :cuenta
  resources :distritos
  resources :operador_registros
  resources :metodo_pago_registros
  resources :vehiculo_registros
  resources :chofer_registros
  resources :tarifario_registros
  resources :feedback_registros
  resources :dirfavorita_registros
  resources :conductor_registros
  resources :cliente_registros
  resources :reservas

  get 'sesion/primario'

  get 'operator/admin'

  get 'iniciar/standar'

  get 'categoria/index'
  get 'iniciar/client'

  get 'iniciar/chofer'
  
  get 'operator/adminhome'
  

    root 'home#index'

end

app/models/chofer_registro.rb
class ChoferRegistro < ActiveRecord::Base
end

app/models/cliente_registro.rb
class ClienteRegistro < ActiveRecord::Base
end

app/models/conductor_registro.rb
class ConductorRegistro < ActiveRecord::Base
end

app/models/cuentum.rb
class Cuentum < ActiveRecord::Base
end

app/models/dirfavorita_registro.rb
class DirfavoritaRegistro < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
end

app/models/feedback_registro.rb
class FeedbackRegistro < ActiveRecord::Base
end

app/models/metodo_pago_registro.rb
class MetodoPagoRegistro < ActiveRecord::Base
end

app/models/operador_registro.rb
class OperadorRegistro < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
    belongs_to :categoria
end

app/models/tarifario_registro.rb
class TarifarioRegistro < ActiveRecord::Base
end

app/models/vehiculo_registro.rb
class VehiculoRegistro < ActiveRecord::Base
end

app/controllers/cliente_registros_controller.rb
class ClienteRegistrosController < ApplicationController
  before_action :set_cliente_registro, only: [:show, :edit, :update, :destroy]

  # GET /cliente_registros
  # GET /cliente_registros.json
  def index
    @cliente_registros = ClienteRegistro.all
  end

  # GET /cliente_registros/1
  # GET /cliente_registros/1.json
  def show
  end

  # GET /cliente_registros/new
  def new
    @cliente_registro = ClienteRegistro.new
  end

  # GET /cliente_registros/1/edit
  def edit
  end

  # POST /cliente_registros
  # POST /cliente_registros.json
  def create
    @cliente_registro = ClienteRegistro.new(cliente_registro_params)

    respond_to do |format|
      if @cliente_registro.save
        format.html { redirect_to @cliente_registro, notice: 'Cliente registro was successfully created.' }
        format.json { render :show, status: :created, location: @cliente_registro }
      else
        format.html { render :new }
        format.json { render json: @cliente_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cliente_registros/1
  # PATCH/PUT /cliente_registros/1.json
  def update
    respond_to do |format|
      if @cliente_registro.update(cliente_registro_params)
        format.html { redirect_to @cliente_registro, notice: 'Cliente registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente_registro }
      else
        format.html { render :edit }
        format.json { render json: @cliente_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliente_registros/1
  # DELETE /cliente_registros/1.json
  def destroy
    @cliente_registro.destroy
    respond_to do |format|
      format.html { redirect_to cliente_registros_url, notice: 'Cliente registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente_registro
      @cliente_registro = ClienteRegistro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_registro_params
      params.require(:cliente_registro).permit(:nombre, :telefono, :apellido, :correo, :contrasena)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/cliente_registros_helper.rb
module ClienteRegistrosHelper
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iniciar_helper.rb
module IniciarHelper
end

app/helpers/operator_helper.rb
module OperatorHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sing_in_helper.rb
module SingInHelper
end

app/views/cliente_registros/_form.html.erb
<%= simple_form_for(@cliente_registro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :telefono %>
    <%= f.input :apellido %>
    <%= f.input :correo %>
    <%= f.input :contrasena %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cliente_registros/edit.html.erb
<h1>Modificar los datos del Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente_registro %> |
<%= link_to 'Back', cliente_registros_path %>

app/views/cliente_registros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relación de Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Apellido</th>
      <th>Correo</th>
      <th>Contrasena</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cliente_registros.each do |cliente_registro| %>
      <tr>
        <td><%= cliente_registro.nombre %></td>
        <td><%= cliente_registro.telefono %></td>
        <td><%= cliente_registro.apellido %></td>
        <td><%= cliente_registro.correo %></td>
        <td><%= cliente_registro.contrasena %></td>
        <td><%= link_to 'Show', cliente_registro %></td>
        <td><%= link_to 'Edit', edit_cliente_registro_path(cliente_registro) %></td>
        <td><%= link_to 'Destroy', cliente_registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Cliente', new_cliente_registro_path %>

app/views/cliente_registros/new.html.erb
<h2>Registrar un Cliente aqui...!</h2>

<%= render 'form' %>

<%= link_to 'Back', cliente_registros_path %>

app/views/cliente_registros/show.html.erb
<h2>Consulta de datos del Cliente</h2>
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente_registro.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente_registro.telefono %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @cliente_registro.apellido %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @cliente_registro.correo %>
</p>

<p>
  <strong>Contrasena:</strong>
  <%= @cliente_registro.contrasena %>
</p>

<%= link_to 'Edit', edit_cliente_registro_path(@cliente_registro) %> |
<%= link_to 'Back', cliente_registros_path %>