config/routes.rb
Rails.application.routes.draw do
  resources :cuenta
  resources :distritos
  resources :operador_registros
  resources :metodo_pago_registros
  resources :vehiculo_registros
  resources :chofer_registros
  resources :tarifario_registros
  resources :feedback_registros
  resources :dirfavorita_registros
  resources :conductor_registros
  resources :cliente_registros
  resources :reservas

  get 'sesion/primario'

  get 'operator/admin'

  get 'iniciar/standar'

  get 'categoria/index'
  get 'iniciar/client'

  get 'iniciar/chofer'
  
  get 'operator/adminhome'
  

    root 'home#index'

end

app/models/chofer_registro.rb
class ChoferRegistro < ActiveRecord::Base
end

app/models/cliente_registro.rb
class ClienteRegistro < ActiveRecord::Base
end

app/models/conductor_registro.rb
class ConductorRegistro < ActiveRecord::Base
end

app/models/cuentum.rb
class Cuentum < ActiveRecord::Base
end

app/models/dirfavorita_registro.rb
class DirfavoritaRegistro < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
end

app/models/feedback_registro.rb
class FeedbackRegistro < ActiveRecord::Base
end

app/models/metodo_pago_registro.rb
class MetodoPagoRegistro < ActiveRecord::Base
end

app/models/operador_registro.rb
class OperadorRegistro < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
    belongs_to :categoria
end

app/models/tarifario_registro.rb
class TarifarioRegistro < ActiveRecord::Base
end

app/models/vehiculo_registro.rb
class VehiculoRegistro < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/operador_registros_controller.rb
class OperadorRegistrosController < ApplicationController
  before_action :set_operador_registro, only: [:show, :edit, :update, :destroy]

  # GET /operador_registros
  # GET /operador_registros.json
  def index
    @operador_registros = OperadorRegistro.all
  end

  # GET /operador_registros/1
  # GET /operador_registros/1.json
  def show
  end

  # GET /operador_registros/new
  def new
    @operador_registro = OperadorRegistro.new
  end

  # GET /operador_registros/1/edit
  def edit
  end

  # POST /operador_registros
  # POST /operador_registros.json
  def create
    @operador_registro = OperadorRegistro.new(operador_registro_params)

    respond_to do |format|
      if @operador_registro.save
        format.html { redirect_to @operador_registro, notice: 'Operador registro was successfully created.' }
        format.json { render :show, status: :created, location: @operador_registro }
      else
        format.html { render :new }
        format.json { render json: @operador_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operador_registros/1
  # PATCH/PUT /operador_registros/1.json
  def update
    respond_to do |format|
      if @operador_registro.update(operador_registro_params)
        format.html { redirect_to @operador_registro, notice: 'Operador registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @operador_registro }
      else
        format.html { render :edit }
        format.json { render json: @operador_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operador_registros/1
  # DELETE /operador_registros/1.json
  def destroy
    @operador_registro.destroy
    respond_to do |format|
      format.html { redirect_to operador_registros_url, notice: 'Operador registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operador_registro
      @operador_registro = OperadorRegistro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operador_registro_params
      params.require(:operador_registro).permit(:codigo, :nombres, :apellidos, :telefono, :cuenta)
    end
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iniciar_helper.rb
module IniciarHelper
end

app/helpers/operador_registros_helper.rb
module OperadorRegistrosHelper
end

app/helpers/operator_helper.rb
module OperatorHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sing_in_helper.rb
module SingInHelper
end

app/views/operador_registros/_form.html.erb
<%= simple_form_for(@operador_registro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :codigo %>
    <%= f.input :nombres %>
    <%= f.input :apellidos %>
    <%= f.input :telefono %>
    <%= f.input :cuenta %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/operador_registros/edit.html.erb
<h1>Modificar los datos del Operador</h1>

<%= render 'form' %>

<%= link_to 'Show', @operador_registro %> |
<%= link_to 'Back', operador_registros_path %>

app/views/operador_registros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relación de Operadores</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Telefono</th>
      <th>Cuenta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operador_registros.each do |operador_registro| %>
      <tr>
        <td><%= operador_registro.codigo %></td>
        <td><%= operador_registro.nombres %></td>
        <td><%= operador_registro.apellidos %></td>
        <td><%= operador_registro.telefono %></td>
        <td><%= operador_registro.cuenta %></td>
        <td><%= link_to 'Show', operador_registro %></td>
        <td><%= link_to 'Edit', edit_operador_registro_path(operador_registro) %></td>
        <td><%= link_to 'Destroy', operador_registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Operador', new_operador_registro_path %>

app/views/operador_registros/new.html.erb
<h1>Registrar un Operador aqui...!</h1>

<%= render 'form' %>

<%= link_to 'Back', operador_registros_path %>

app/views/operador_registros/show.html.erb
<h1>Consultar los datos del Operador</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @operador_registro.codigo %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @operador_registro.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @operador_registro.apellidos %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @operador_registro.telefono %>
</p>

<p>
  <strong>Cuenta:</strong>
  <%= @operador_registro.cuenta %>
</p>

<%= link_to 'Edit', edit_operador_registro_path(@operador_registro) %> |
<%= link_to 'Back', operador_registros_path %>