config/routes.rb
Rails.application.routes.draw do
  resources :cuenta
  resources :distritos
  resources :operador_registros
  resources :metodo_pago_registros
  resources :vehiculo_registros
  resources :chofer_registros
  resources :tarifario_registros
  resources :feedback_registros
  resources :dirfavorita_registros
  resources :conductor_registros
  resources :cliente_registros
  resources :reservas

  get 'sesion/primario'

  get 'operator/admin'

  get 'iniciar/standar'

  get 'categoria/index'
  get 'iniciar/client'

  get 'iniciar/chofer'
  
  get 'operator/adminhome'
  

    root 'home#index'

end

app/models/chofer_registro.rb
class ChoferRegistro < ActiveRecord::Base
end

app/models/cliente_registro.rb
class ClienteRegistro < ActiveRecord::Base
end

app/models/conductor_registro.rb
class ConductorRegistro < ActiveRecord::Base
end

app/models/cuentum.rb
class Cuentum < ActiveRecord::Base
end

app/models/dirfavorita_registro.rb
class DirfavoritaRegistro < ActiveRecord::Base
end

app/models/distrito.rb
class Distrito < ActiveRecord::Base
end

app/models/feedback_registro.rb
class FeedbackRegistro < ActiveRecord::Base
end

app/models/metodo_pago_registro.rb
class MetodoPagoRegistro < ActiveRecord::Base
end

app/models/operador_registro.rb
class OperadorRegistro < ActiveRecord::Base
end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
    belongs_to :categoria
end

app/models/tarifario_registro.rb
class TarifarioRegistro < ActiveRecord::Base
end

app/models/vehiculo_registro.rb
class VehiculoRegistro < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tarifario_registros_controller.rb
class TarifarioRegistrosController < ApplicationController
  before_action :set_tarifario_registro, only: [:show, :edit, :update, :destroy]

  # GET /tarifario_registros
  # GET /tarifario_registros.json
  def index
    @tarifario_registros = TarifarioRegistro.all
  end

  # GET /tarifario_registros/1
  # GET /tarifario_registros/1.json
  def show
  end

  # GET /tarifario_registros/new
  def new
    @tarifario_registro = TarifarioRegistro.new
  end

  # GET /tarifario_registros/1/edit
  def edit
  end

  # POST /tarifario_registros
  # POST /tarifario_registros.json
  def create
    @tarifario_registro = TarifarioRegistro.new(tarifario_registro_params)

    respond_to do |format|
      if @tarifario_registro.save
        format.html { redirect_to @tarifario_registro, notice: 'Tarifario registro was successfully created.' }
        format.json { render :show, status: :created, location: @tarifario_registro }
      else
        format.html { render :new }
        format.json { render json: @tarifario_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tarifario_registros/1
  # PATCH/PUT /tarifario_registros/1.json
  def update
    respond_to do |format|
      if @tarifario_registro.update(tarifario_registro_params)
        format.html { redirect_to @tarifario_registro, notice: 'Tarifario registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarifario_registro }
      else
        format.html { render :edit }
        format.json { render json: @tarifario_registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tarifario_registros/1
  # DELETE /tarifario_registros/1.json
  def destroy
    @tarifario_registro.destroy
    respond_to do |format|
      format.html { redirect_to tarifario_registros_url, notice: 'Tarifario registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarifario_registro
      @tarifario_registro = TarifarioRegistro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarifario_registro_params
      params.require(:tarifario_registro).permit(:distrito_origen, :distrito_origen, :tarifa)
    end
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/helpers/distritos_helper.rb
module DistritosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/iniciar_helper.rb
module IniciarHelper
end

app/helpers/operator_helper.rb
module OperatorHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sesion_helper.rb
module SesionHelper
end

app/helpers/sing_in_helper.rb
module SingInHelper
end

app/helpers/tarifario_registros_helper.rb
module TarifarioRegistrosHelper
end

app/views/tarifario_registros/_form.html.erb
<%= simple_form_for(@tarifario_registro) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :distrito_origen %>
    <%= f.input :distrito_origen %>
    <%= f.input :tarifa %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tarifario_registros/edit.html.erb
<h1>Modificar los datos de la Tarifa</h1>

<%= render 'form' %>

<%= link_to 'Show', @tarifario_registro %> |
<%= link_to 'Back', tarifario_registros_path %>

app/views/tarifario_registros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relación de Tarifas</h1>

<table>
  <thead>
    <tr>
      <th>Distrito origen</th>
      <th>Distrito origen</th>
      <th>Tarifa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tarifario_registros.each do |tarifario_registro| %>
      <tr>
        <td><%= tarifario_registro.distrito_origen %></td>
        <td><%= tarifario_registro.distrito_origen %></td>
        <td><%= tarifario_registro.tarifa %></td>
        <td><%= link_to 'Show', tarifario_registro %></td>
        <td><%= link_to 'Edit', edit_tarifario_registro_path(tarifario_registro) %></td>
        <td><%= link_to 'Destroy', tarifario_registro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Registrar Tarifa', new_tarifario_registro_path %>

app/views/tarifario_registros/new.html.erb
<h1>Registrar una Tarifa</h1>

<%= render 'form' %>

<%= link_to 'Back', tarifario_registros_path %>

app/views/tarifario_registros/show.html.erb
<h1>Consultar los datos de la Tarifa</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Distrito origen:</strong>
  <%= @tarifario_registro.distrito_origen %>
</p>

<p>
  <strong>Distrito origen:</strong>
  <%= @tarifario_registro.distrito_origen %>
</p>

<p>
  <strong>Tarifa:</strong>
  <%= @tarifario_registro.tarifa %>
</p>

<%= link_to 'Edit', edit_tarifario_registro_path(@tarifario_registro) %> |
<%= link_to 'Back', tarifario_registros_path %>